### ISSUE TITLE
classFactory() error  when installing cgl_tools-2.0.zip

### ISSUE THREAD

**Issue by DrDids** [fgianoli/copernicus_tools#2]
I tried to install plugin cgl_tools-2.0.zip to QGIS from the zip file: error below. 

Couldn't load plugin 'cgl_tools' due to an error when calling its classFactory() method 

ImportError: cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' (/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/urllib3/util/ssl_.py) 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/__init__.py", line 49, in classFactory
    from .CGL_tools import CGL_toolsPlugin
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/CGL_tools.py", line 58, in 
    from .CGL_tools_provider import CGL_toolsProvider
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/CGL_tools_provider.py", line 34, in 
    from .CGL_tools_algorithm import LandCoverDownload
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/CGL_tools_algorithm.py", line 60, in 
    import boto3
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/boto3/__init__.py", line 17, in 
    from boto3.session import Session
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/boto3/session.py", line 17, in 
    import botocore.session
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/session.py", line 26, in 
    import botocore.client
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/client.py", line 15, in 
    from botocore import waiter, xform_name
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/waiter.py", line 18, in 
    from botocore.docs.docstring import WaiterDocstring
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/docs/__init__.py", line 15, in 
    from botocore.docs.service import ServiceDocumenter
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/docs/service.py", line 14, in 
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/docs/client.py", line 14, in 
    from botocore.docs.example import ResponseExampleDocumenter
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/docs/example.py", line 13, in 
    from botocore.docs.shape import ShapeDocumenter
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/docs/shape.py", line 19, in 
    from botocore.utils import is_json_value_header
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/utils.py", line 34, in 
    import botocore.httpsession
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs/botocore/httpsession.py", line 21, in 
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' (/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/urllib3/util/ssl_.py)

Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.28.7-Firenze Firenze, 62cbdb06b6 

Python Path:
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sense_detection
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/pyqtgraph
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/site-packages
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/apps
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/eo4qapps
.
/Users/lgzdl/Library/Application Support/gis4wrf/python39/lib/python3.9/site-packages
/Users/lgzdl/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cgl_tools/extlibs

**Comment by Marwe** [comment]
I have a similar error:

```
Couldn't load plugin 'cgl_tools' due to an error when calling its classFactory() method 
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/usr/lib/python3/dist-packages/urllib3/util/ssl_.py) 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
[...]
```

Installing the system packages did the trick (debian/Ubuntu) here:
```bash
sudo apt install python3-botocore python3-boto3
```
Creating a python environment via [qgis-venv-creator](https://github.com/GispoCoding/qgis-venv-creator)and installing boto3 and botocore via pip also worked for me.
